#!/usr/bin/env node
/**
 * Harbor — the SceneScout demo app.
 *
 * A small, invented order desk with a handful of deliberately seeded defects,
 * one per kind of thing SceneScout finds. Three roles (clerk, manager,
 * auditor) and an approval queue give a multi-role run something to hand off,
 * and the separate areas (orders, approvals, inventory, customers, audit log)
 * give parallel agents something to split. It exists so you can watch a run
 * without pointing the tool at anything real, and so the sample report in
 * examples/ can be regenerated by anyone:  npm run demo
 *
 * No dependencies, in-memory data, loopback only. The seeded defects are
 * listed in demo-app/README.md — do not read it first if you want to see what
 * a run discovers on its own.
 */
import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const publicDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "public");
const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css",
  ".js": "text/javascript",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
};

const ROLES = ["clerk", "manager", "auditor"];

export function createDemoServer() {
  let nextId = 1043;
  const orders = [
    { id: 1042, customer: "Marlow & Finch", items: 3, total: 184.5, status: "open", notes: "" },
    { id: 1041, customer: "Tidewater Supply", items: 12, total: 1290.0, status: "open", notes: "Deliver to dock B." },
    { id: 1040, customer: "Juniper Books", items: 1, total: 22.0, status: "shipped", notes: "" },
    { id: 1039, customer: "Calloway Hardware", items: 7, total: 412.75, status: "shipped", notes: "" },
    { id: 1038, customer: "Brightwater Cafe", items: 40, total: 2380.0, status: "pending", notes: "Standing order, needs sign-off." },
    { id: 1037, customer: "Quarry Lane Studio", items: 18, total: 1125.5, status: "pending", notes: "" },
  ];
  const inventory = [
    { sku: "HB-101", name: "Packing tape", qty: 120 },
    { sku: "HB-102", name: "Shipping labels", qty: 9 },
    { sku: "HB-103", name: "Corner protectors", qty: 10 },
    { sku: "HB-104", name: "Pallet wrap", qty: 3 },
    { sku: "HB-105", name: "Kraft boxes, large", qty: 64 },
    { sku: "HB-106", name: "Void fill", qty: 250 },
  ];
  const customers = [
    { id: 1, name: "Marlow & Finch", city: "Bristol", since: 2019 },
    { id: 2, name: "Tidewater Supply", city: "Plymouth", since: 2021 },
    { id: 3, name: "Juniper Books", city: "Bath", since: 2022 },
    { id: 4, name: "Calloway Hardware", city: "Exeter", since: 2018 },
    { id: 5, name: "Brightwater Cafe", city: "Truro", since: 2023 },
    { id: 6, name: "Quarry Lane Studio", city: "Falmouth", since: 2024 },
  ];
  const audit = [
    // Newest first, the order the page shows them in.
    { at: "09:14", role: "clerk", action: "requested approval", order: 1037 },
    { at: "09:02", role: "clerk", action: "requested approval", order: 1038 },
  ];
  const clock = () => new Date().toISOString().slice(11, 16);
  const log = (role, action, order) => audit.unshift({ at: clock(), role, action, order });
  /** The signed-in role. No cookie means clerk, which is how the app behaved before it had roles. */
  const roleOf = (req) => {
    const m = /(?:^|;\s*)harbor_role=([a-z]+)/.exec(req.headers.cookie ?? "");
    return m && ROLES.includes(m[1]) ? m[1] : "clerk";
  };
  const json = (res, status, body) => {
    res.writeHead(status, { "content-type": "application/json" });
    res.end(JSON.stringify(body));
  };
  /** Parsed JSON body, or {} — never rejects, never hangs, never grows past 64 KiB. */
  const readBody = (req) =>
    new Promise((resolve) => {
      const chunks = [];
      let size = 0;
      const done = (value) => resolve(value);
      req.on("data", (c) => {
        size += c.length;
        if (size > 64 * 1024) {
          req.destroy();
          return done({});
        }
        chunks.push(c);
      });
      req.on("end", () => {
        try {
          done(JSON.parse(Buffer.concat(chunks).toString() || "{}"));
        } catch {
          done({});
        }
      });
      // A client that disconnects mid-body must not leave the handler waiting forever.
      req.on("error", () => done({}));
      req.on("aborted", () => done({}));
    });

  const handle = async (req, res) => {
    const url = new URL(req.url ?? "/", "http://localhost");
    const p = url.pathname;
    const role = roleOf(req);
    const writes = req.method !== "GET" && req.method !== "HEAD";
    // Auditors read everything and change nothing — enforced here, not by hiding buttons.
    if (writes && role === "auditor" && p.startsWith("/api/") && p !== "/api/signin") return json(res, 403, { error: "Auditors have read-only access" });

    if (p === "/api/me" && req.method === "GET") return json(res, 200, { role });
    if (p === "/api/signin" && req.method === "POST") {
      const body = await readBody(req);
      if (!ROLES.includes(body.role)) return json(res, 400, { error: "Unknown role" });
      res.writeHead(200, { "content-type": "application/json", "set-cookie": `harbor_role=${body.role}; Path=/; SameSite=Lax; HttpOnly` });
      return res.end(JSON.stringify({ role: body.role }));
    }
    if (p === "/api/approvals" && req.method === "GET")
      return json(
        res,
        200,
        orders.filter((o) => o.status === "pending"),
      );
    if (p === "/api/inventory" && req.method === "GET") {
      const sort = url.searchParams.get("sort");
      const rows = [...inventory];
      // SEEDED DEFECT: quantity is compared as text, so 10 sorts before 9.
      if (sort === "qty") rows.sort((a, b) => String(a.qty).localeCompare(String(b.qty)));
      if (sort === "name") rows.sort((a, b) => a.name.localeCompare(b.name));
      return json(res, 200, rows);
    }
    if (p === "/api/customers" && req.method === "GET") return json(res, 200, customers);
    if (p === "/api/audit" && req.method === "GET") {
      if (role === "clerk") return json(res, 403, { error: "The audit log is for managers and auditors" });
      return json(res, 200, audit);
    }
    const act = p.match(/^\/api\/orders\/(\d+)\/(request-approval|approve|reject)$/);
    if (act && req.method === "POST") {
      const order = orders.find((o) => o.id === Number(act[1]));
      if (!order) return json(res, 404, { error: "Order not found" });
      if (act[2] === "request-approval") {
        if (order.status !== "open") return json(res, 409, { error: `Only an open order can be sent for approval (this one is ${order.status})` });
        order.status = "pending";
        log(role, "requested approval", order.id);
        return json(res, 200, order);
      }
      if (order.status !== "pending") return json(res, 409, { error: "This order is not waiting for approval" });
      // SEEDED DEFECT: reject checks for a manager; approve does not. The page
      // hides the Approve button from other roles, but the endpoint accepts them.
      if (act[2] === "reject" && role !== "manager") return json(res, 403, { error: "Only a manager can reject an order" });
      order.status = act[2] === "approve" ? "approved" : "rejected";
      log(role, act[2] === "approve" ? "approved" : "rejected", order.id);
      return json(res, 200, order);
    }

    if (p === "/api/orders" && req.method === "GET") {
      const status = url.searchParams.get("status");
      // SEEDED DEFECT: the "archived" filter hits a code path that throws.
      if (status === "archived") return json(res, 500, { error: "Internal Server Error" });
      return json(res, 200, status ? orders.filter((o) => o.status === status) : orders);
    }
    if (p === "/api/orders" && req.method === "POST") {
      const body = await readBody(req);
      // SEEDED DEFECT: no idempotency — two quick submits create two orders.
      const order = { id: nextId++, customer: String(body.customer ?? ""), items: Number(body.items ?? 1), total: 0, status: "open", notes: "" };
      orders.unshift(order);
      log(role, "created", order.id);
      return json(res, 201, order);
    }
    const one = p.match(/^\/api\/orders\/(\d+)$/);
    if (one) {
      const order = orders.find((o) => o.id === Number(one[1]));
      if (!order) return json(res, 404, { error: "Order not found" });
      if (req.method === "GET") return json(res, 200, order);
      if (req.method === "PUT") {
        // Only the editable field: a body must not be able to rewrite an order's id.
        const body = await readBody(req);
        if (typeof body.notes === "string") order.notes = body.notes.slice(0, 2000);
        return json(res, 200, order);
      }
      if (req.method === "DELETE") {
        if (role !== "manager") return json(res, 403, { error: "Only a manager can delete an order" });
        orders.splice(orders.indexOf(order), 1);
        return json(res, 200, { ok: true });
      }
    }
    if (p === "/api/workspace" && req.method === "DELETE") {
      if (role !== "manager") return json(res, 403, { error: "Only a manager can clear the workspace" });
      orders.length = 0;
      return json(res, 200, { ok: true });
    }

    // Static files, fenced to public/.
    const rel = p === "/" ? "/index.html" : p;
    const file = path.resolve(publicDir, `.${path.posix.normalize(rel)}`);
    if (file.startsWith(publicDir + path.sep) && fs.existsSync(file) && fs.statSync(file).isFile()) {
      res.writeHead(200, { "content-type": TYPES[path.extname(file)] ?? "application/octet-stream" });
      return res.end(fs.readFileSync(file));
    }
    res.writeHead(404, { "content-type": "text/html; charset=utf-8" });
    res.end("<!doctype html><title>Not found</title><h1>404</h1><p>Nothing here.</p>");
  };

  // A malformed request target or a file that vanishes mid-read must produce a
  // 500, not an unhandled rejection that takes the whole demo down.
  const server = http.createServer((req, res) => {
    handle(req, res).catch(() => {
      if (!res.headersSent) res.writeHead(500, { "content-type": "text/plain" });
      res.end("Internal Server Error");
    });
  });
  server.on("clientError", (_err, socket) => socket.destroy());
  return server;
}

// Run directly: `node demo-app/server.mjs [port]`
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const port = Number(process.argv[2] ?? process.env.PORT ?? 4173);
  createDemoServer().listen(port, "127.0.0.1", () => {
    console.log(`Harbor demo app on http://127.0.0.1:${port}\nTry:  /scenescout --url http://127.0.0.1:${port}`);
  });
}
