#!/usr/bin/env node
/**
 * Harbor — the SceneScout demo app.
 *
 * A small, invented order desk with a handful of deliberately seeded defects,
 * one per kind of thing SceneScout finds. It exists so you can watch a run
 * without pointing the tool at anything real, and so the sample report in
 * examples/ can be regenerated by anyone:  npm run demo
 *
 * No dependencies, in-memory data, loopback only. The seeded defects are
 * listed in demo-app/README.md — do not read it first if you want to see what
 * a run discovers on its own.
 */
import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const publicDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "public");
const TYPES = { ".html": "text/html; charset=utf-8", ".css": "text/css", ".js": "text/javascript", ".svg": "image/svg+xml" };

export function createDemoServer() {
  let nextId = 1043;
  const orders = [
    { id: 1042, customer: "Marlow & Finch", items: 3, total: 184.5, status: "open", notes: "" },
    { id: 1041, customer: "Tidewater Supply", items: 12, total: 1290.0, status: "open", notes: "Deliver to dock B." },
    { id: 1040, customer: "Juniper Books", items: 1, total: 22.0, status: "shipped", notes: "" },
    { id: 1039, customer: "Calloway Hardware", items: 7, total: 412.75, status: "shipped", notes: "" },
  ];
  const json = (res, status, body) => {
    res.writeHead(status, { "content-type": "application/json" });
    res.end(JSON.stringify(body));
  };
  /** Parsed JSON body, or {} — never rejects, never hangs, never grows past 64 KiB. */
  const readBody = (req) =>
    new Promise((resolve) => {
      const chunks = [];
      let size = 0;
      const done = (value) => resolve(value);
      req.on("data", (c) => {
        size += c.length;
        if (size > 64 * 1024) {
          req.destroy();
          return done({});
        }
        chunks.push(c);
      });
      req.on("end", () => {
        try {
          done(JSON.parse(Buffer.concat(chunks).toString() || "{}"));
        } catch {
          done({});
        }
      });
      // A client that disconnects mid-body must not leave the handler waiting forever.
      req.on("error", () => done({}));
      req.on("aborted", () => done({}));
    });

  const handle = async (req, res) => {
    const url = new URL(req.url ?? "/", "http://localhost");
    const p = url.pathname;

    if (p === "/api/orders" && req.method === "GET") {
      const status = url.searchParams.get("status");
      // SEEDED DEFECT: the "archived" filter hits a code path that throws.
      if (status === "archived") return json(res, 500, { error: "Internal Server Error" });
      return json(res, 200, status ? orders.filter((o) => o.status === status) : orders);
    }
    if (p === "/api/orders" && req.method === "POST") {
      const body = await readBody(req);
      // SEEDED DEFECT: no idempotency — two quick submits create two orders.
      const order = { id: nextId++, customer: String(body.customer ?? ""), items: Number(body.items ?? 1), total: 0, status: "open", notes: "" };
      orders.unshift(order);
      return json(res, 201, order);
    }
    const one = p.match(/^\/api\/orders\/(\d+)$/);
    if (one) {
      const order = orders.find((o) => o.id === Number(one[1]));
      if (!order) return json(res, 404, { error: "Order not found" });
      if (req.method === "GET") return json(res, 200, order);
      if (req.method === "PUT") {
        // Only the editable field: a body must not be able to rewrite an order's id.
        const body = await readBody(req);
        if (typeof body.notes === "string") order.notes = body.notes.slice(0, 2000);
        return json(res, 200, order);
      }
      if (req.method === "DELETE") {
        orders.splice(orders.indexOf(order), 1);
        return json(res, 200, { ok: true });
      }
    }
    if (p === "/api/workspace" && req.method === "DELETE") {
      orders.length = 0;
      return json(res, 200, { ok: true });
    }

    // Static files, fenced to public/.
    const rel = p === "/" ? "/index.html" : p;
    const file = path.resolve(publicDir, `.${path.posix.normalize(rel)}`);
    if (file.startsWith(publicDir + path.sep) && fs.existsSync(file) && fs.statSync(file).isFile()) {
      res.writeHead(200, { "content-type": TYPES[path.extname(file)] ?? "application/octet-stream" });
      return res.end(fs.readFileSync(file));
    }
    res.writeHead(404, { "content-type": "text/html; charset=utf-8" });
    res.end("<!doctype html><title>Not found</title><h1>404</h1><p>Nothing here.</p>");
  };

  // A malformed request target or a file that vanishes mid-read must produce a
  // 500, not an unhandled rejection that takes the whole demo down.
  const server = http.createServer((req, res) => {
    handle(req, res).catch(() => {
      if (!res.headersSent) res.writeHead(500, { "content-type": "text/plain" });
      res.end("Internal Server Error");
    });
  });
  server.on("clientError", (_err, socket) => socket.destroy());
  return server;
}

// Run directly: `node demo-app/server.mjs [port]`
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const port = Number(process.argv[2] ?? process.env.PORT ?? 4173);
  createDemoServer().listen(port, "127.0.0.1", () => {
    console.log(`Harbor demo app on http://127.0.0.1:${port}\nTry:  /scenescout --url http://127.0.0.1:${port}`);
  });
}
